#! /usr/bin/env python

import sys
import re
import os
import subprocess

OUTPUT_SIZE = "350x560^"
OUTPUT_DIRECTORY = "/home/teddy/projects/dixit/frontend/cards"
RELATIVE_PATH = "cards"

def change_ext(filename, new_ext):
    """return a new filename, with the extension changed.
    """
    return re.sub(r"\.\w+$", new_ext, filename)

def run_standardize(directory):
    files = os.listdir(directory)
    for index, filename in enumerate(files):
        output_filename = "{}_{}.png".format(directory, index)
        output_path = os.path.join(OUTPUT_DIRECTORY, output_filename)
        subprocess.run(["magick",
                        os.path.join(directory, filename),
                        "-resize",
                        OUTPUT_SIZE,
                        output_path])

        print("('{}'),".format(output_filename))


def main():
    for dirname in sys.argv[1:]:
        run_standardize(dirname)

if __name__ == "__main__":
    main()
